# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d0a3402dd44a780c00aa42fc1560917ea58c9f7beba0a19a618d04ebc1391d898a8e7743fdd55e893b30187ac07b148e60b3d8abbd1ef6382be3277f075a52e

test:
  secret_key_base: 93988962bd9c04146f89cb486179f4588e46cf301a44d99832d1fb522e03916273b7e3fc4c41005083385fc69502c928cebc5931e9a1dc3628c5ae8806715645

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
